### ISSUE TITLE
smoothscreen WxH not accurately displayed

### ISSUE THREAD

**Issue by angilbert** [david-pfx/PuzzleScriptNext#148]
**Describe the bug**
smoothscreen WxH not accurately displayed

**Reproduction Steps**
1. Load https://david-pfx.github.io/PuzzleScriptNext/src/editor.html
2. Load ENIGMASH (Example game)
3. Adjust prelude so it contains "smoothscreen 7x7"
4. Save and Run game
5. Notice the display is not 7x7 (it appears to be 8 sprites wide and 7-and-a-bit high)

**What did you expect would happen?**
smoothscreen behaves like zoomscreen and displays 7x7 sprites accurately

**OS & Browser version, desktop/mobile**
Chrome/Mac/Desktop

**Screenshots, example projects, other relevant issues, etc.**
Here is a screenshot comparing smoothscreen and zoomscreen side-by-side...
<img width="961" alt="Screenshot 2025-01-04 at 16 46 36" src="https://github.com/user-attachments/assets/5399c514-0d54-4324-bb4d-da275eb225d7" />

**Comment by angilbert** [comment]
Also the status_line is not displayed correctly in a bar below the smoothscreen area (note, this is the same residual issue described in https://github.com/david-pfx/PuzzleScriptNext/issues/124 - but here, much easier to reproduce with ENIGMASH)...

<img width="920" alt="Screenshot 2025-01-04 at 17 05 03" src="https://github.com/user-attachments/assets/b2bf60e6-5c4c-477a-9d9d-e098f8956d72" />

**Comment by david-pfx** [comment]
Reproduced. Thanks!

The behaviour is supposed to be identical to 
PS+, but it ain't. Will fix.

**Comment by david-pfx** [comment]
Simple bug: the clip region for smoothscreen calculated wrong.
Fixed.

**Comment by angilbert** [comment]
Confirmed fix. BUT the status_line issue is still observed. 
Add status_line to the prelude - and the display height extends into the space reserved for the status bar

Here is a screenshot of enigmash with:
```
smoothscreen 7x7
status_line
```
<img width="860" alt="Screenshot 2025-01-08 at 13 46 26" src="https://github.com/user-attachments/assets/d01a212c-deea-474d-8085-120175e7b82b" />

**Comment by david-pfx** [comment]
Yes, status_line needs a bit of love. It's currently incompatible with smoothscreen because of this clipping region problem. It has other issues. Not a quick fix.
